services/libfuzzer/Dockerfile, services/libfuzzer/coverage.sh, services/libfuzzer/libfuzzer.sh
This PR adds the following features and fixes:
- Add support for S3_PROJECT to obtain corpus from S3 and synchronize files back for progress sharing and corpus evolving
- Add support for running multiple instances, defaulting to number of CPU threads
- Add auto-reduce support
- Add stats support
- Adjust tool name to match naming scheme in the backend
- Remove requirement for having mozilla-central around when generating coverage
- Remove some default options being passed to libFuzzer as the harness passes them already
=> libFuzzer improvements

services/funfuzz/Dockerfile, services/funfuzz/funfuzz.sh, services/funfuzz/recipes/get_moz_repos.sh, services/funfuzz/recipes/get_non_moz_repos.sh, services/funfuzz/recipes/get_pip_packages.sh, services/funfuzz/recipes/get_rust.sh, services/funfuzz/recipes/install_prerequisites.sh, services/funfuzz/recipes/set_bashrc_options.sh, services/funfuzz/recipes/set_mercurial_config.sh, services/funfuzz/recipes/set_vim_config.sh, services/funfuzz/recipes/ssh_fuzzmanager_setup.sh, services/funfuzz/setup.sh, services/funfuzz/tests/funfuzz_command_test.yaml, services/funfuzz/tests/funfuzz_metadata_test.yaml
Here's the port of funfuzz.sh to Orion with the following output
```
$ docker run -it --rm mozillasecurity/funfuzz:latest
bash: ccache: command not found
$ python3 -u -m funfuzz --version
Platform details: Linux 8fe850dce50a 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64
hg info: Mercurial Distributed SCM (version 4.8.1)
git info: git version 2.17.1
Python version: 3.6.7
Number of cores visible to OS: 4
Free space (GB): 59.11
Corefile size (soft limit, hard limit) is: (-1, -1)
Usage: __main__.py [options]
__main__.py: error: no such option: --version
$
```
As can be seen, funfuzz is installed and can be run after the docker initialises. There is a bunch of issues to be looked into prior to deployment though, e.g. why `ccache` is not found/installed even though …
=> Make the funfuzz Python package able to be run in the Docker, by porting funfuzz.sh

services/credstash/Dockerfile
This also pre-compiles python libs to reduce the final image size. (119Mb -> 86Mb).
I removed the clean-up step from the builder too. It's a temporary image anyways, so it just seems like extra work.
Fixes #33.
=> [credstash] Add libssl so `credstash get` works

base/linux/fuzzos/recipes/fuzzos.sh
This is to work around occasional issues like https://github.com/boto/boto/issues/1868
=> Set number of attempts when reading from EC2 metadata service.

base/linux/fuzzos/README.md, base/linux/fuzzos/recipes/berglas.sh, base/linux/fuzzos/setup.sh
[Berglas](https://github.com/GoogleCloudPlatform/berglas) looks like the best equivalent for credstash in GCP. I've already set it up and it works fine. The pre-compiled binary is statically linked and 11Mb.
=> Add Berglas for secrets storage in GCP

base/linux/fuzzos/recipes/common.sh, services/libfuzzer/libfuzzer.sh
This should add support for setting SHIP=GCE to the `common.sh` functions and libFuzzer.
=> [libFuzzer] Add support for SHIP=GCE

.travis.yml, base/linux/fuzzos/recipes/fuzzfetch.sh, base/linux/fuzzos/recipes/grcov.sh, base/linux/fuzzos/recipes/halfempty.sh, base/linux/fuzzos/recipes/honggfuzz.sh, base/linux/fuzzos/recipes/htop.sh, base/linux/fuzzos/recipes/rg.sh, base/linux/fuzzos/recipes/rr.sh, services/libfuzzer/libfuzzer.sh
Fixes setup failure
```
$ travis_retry sudo pip3 install -r requirements.txt
Collecting pyyaml>=4.2b1 (from -r requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz (265kB)
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
ImportError: No module named 'setuptools'
```
=> [ci] Update .travis.yml

base/linux/fuzzos/recipes/pernosco_submit.sh, services/funfuzz/recipes/get_pip_packages.sh, services/funfuzz/recipes/install_prerequisites.sh, services/funfuzz/recipes/set_mercurial_config.sh
Here are the updates for funfuzz setup scripts since the last attempt. We'll need at least these minimal changes before it is attempted to switchover to Orion fully.
=> Update funfuzz scripts in Orion for 201912.

services/grizzly/Dockerfile, services/grizzly/launch-grizzly-worker.sh, services/grizzly/launch-grizzly.sh, services/grizzly/recipes/fuzzing_tc.sh, services/grizzly/recipes/setup.sh
If environment variables are set by Taskcluster, environment variables will be fetched and set from the fuzzing config repo.
Depends on https://github.com/MozillaSecurity/fuzzing-tc/pull/37
=> [grizzly] Install and use launcher for Taskcluster tasks.

recipes/linux/gcov-7.sh, recipes/linux/gcov-8.sh, services/grizzly/launch-grizzly-worker.sh, services/grizzly/setup.sh
The Ubuntu version of gcov is once again causing issues with grcov.  This PR downloads and installs gcov-8 from the Mozilla build server and uses that when running grcov.
=> Use gcov-7 from Mozilla Build Server

services/libfuzzer/README.md, services/libfuzzer/setup-target.sh
Fuzzfetch args `--tests gtest` has been changed to `--gtest` in https://github.com/MozillaSecurity/fuzzfetch/pull/69
=> Update fuzzfetch gtest arguments

services/grizzly/setup.sh
=> [grizzly] Remove gvfs to workaround bug 1682934 (TSan fails to start)

base/linux/etc/pip.conf, recipes/linux/fuzzing_tc.sh, recipes/linux/fuzzmanager.sh, services/funfuzz/Dockerfile, services/funfuzz/setup.sh, services/grizzly/Dockerfile, services/grizzly/setup.sh, services/langfuzz/Dockerfile, services/langfuzz/service.yaml, services/langfuzz/setup.sh, services/libfuzzer/Dockerfile, services/libfuzzer/setup.sh
And also:
- don't keep a clone of FuzzManager unless needed, just install it
- disable progress-bar for all pip install
=> Use fuzzing-decision from the tree, instead of cloning from github

recipes/linux/common.sh, services/grizzly-reduce-monitor/src/grizzly_reduce_monitor/monitor.py, services/grizzly/launch-grizzly-worker.sh, services/grizzly/launch-grizzly.sh, services/grizzly/setup.sh
This revision will still make credstash available. Once bearspray is switched over, credstash can be removed.
=> [grizzly] Use Taskcluster secrets instead of credstash

services/bugmon/Dockerfile, services/ci-node-10/Dockerfile, services/ci-node-12/Dockerfile, services/funfuzz/Dockerfile, services/fuzzing-decision/Dockerfile, services/fuzzing-decision/src/fuzzing_decision/decision/cli.py, services/fuzzmanager/Dockerfile, services/gr-css-reports/Dockerfile, services/grizzly/Dockerfile, services/langfuzz/Dockerfile, services/libfuzzer/Dockerfile, services/orion-builder/Dockerfile, services/orion-builder/src/orion_builder/build.py
- switch DEBIAN_FRONTEND to an ARG (build-time only) instead of ENV (build and run-time)
- switch fuzzing-decision to use alpine (80% smaller image)
- fix bug in orion-builder Dockerfile, if configure failed it would have been masked
- add support in orion-builder for `docker build --build-arg`  (already supported by task-boot, passed through)
=> Miscellaneous changes in fuzzing-decision and orion-builder

services/orion-decision/src/orion_decision/git.py, services/orion-decision/tests/test_gitrepo.py
Fetch the single revisions before/after. This should always work, even if it does an unnecessary fetch.
=> [orion-decision] Simplify git fetching.

.pre-commit-config.yaml, services/orion-decision/src/orion_decision/orion.py, services/orion-decision/src/orion_decision/scheduler.py, services/orion-decision/src/orion_decision/task_templates/recipe_test.yaml, services/orion-decision/tests/fixtures/services03/test1/Dockerfile, services/orion-decision/tests/fixtures/services07/test1/Dockerfile, services/orion-decision/tests/fixtures/services07/test1/service.yaml, services/orion-decision/tests/fixtures/services07/test2/Dockerfile, services/orion-decision/tests/fixtures/services07/test2/service.yaml, services/orion-decision/tests/test_orion.py, services/orion-decision/tests/test_scheduler.py, services/test-recipes/Dockerfile, services/test-recipes/Dockerfile-fuzzing_tc, services/test-recipes/launch.sh
This includes recipes directly in the dependency graph, instead of indirectly as path-deps of services.
=> [orion-decison] Add recipe tests.

recipes/linux/js32_deps.sh, services/langfuzz/Dockerfile, services/langfuzz/setup.sh
Also adds a recipe for 32-bit libs required by spidermonkey x86 builds.
=> [langfuzz] Use recipes rather than duplicating code in langfuzz.

services/gr-css-reports/launch.sh
Updates the gr-css-reports image to pull gr.css from npm.  *Note, gr.css now accepts prefixed env variables for arguments so the command has been updated.
=> [gr-css-reports] Fetch gr.css from @mozillasecurity npm

services/ci-py-38-win/setup.sh, services/orion-decision/src/orion_decision/ci_scheduler.py, services/orion-decision/tests/test_cischeduler.py
- pass CI scopes only once
- patch tox to workaround https://github.com/tox-dev/tox/issues/1982
=> Fix CI matrix

services/js-tests-distiller/launch.sh, services/js-tests-distiller/setup.sh
This creates another archive that is used by the non-distiller jobs. We can evaluate later if we still need this, but for now I'd like to simply migrate it to get be able to proceed with decommissioning the old build jobs.
I will also create a PR to add the resulting zip as an artifact.
=> [jstests] Migrate legacy test bundling code to distiller job

services/libfuzzer/libfuzzer.sh
Fix this problem when running `firefox -xpcshell -merge=1`
```
FUZZER=client.js firefox -xpcshell -merge=1 tests queues
INFO: Seed: 2171328303
INFO: Loaded 1 modules   (1264857 inline 8-bit counters): 1264857 [0x7fa5708798b0, 0x7fa5709ae589), 
INFO: Loaded 1 PC tables (1264857 PCs): 1264857 [0x7fa5709ae590,0x7fa571cfb320), 
MERGE-OUTER: 5553 files, 85 in the initial corpus, 0 processed earlier
MERGE-OUTER: attempt 1
*** You are running in headless mode.
Running Fuzzer tests...
Fuzzing Interface: Error: No testing callback found
```
=> Fix xpcshell merge command line.

services/fuzzing-decision/src/fuzzing_decision/decision/__init__.py, services/fuzzing-decision/src/fuzzing_decision/decision/pool.py
Pushing to the fuzzing config repo has timed out because there are so many hook fires to search under for tasks. Only search recent hook fires. Limit to 2 days, since our max cycle-time is 1.
=> When cycling pools, only look for tasks launched by hooks in the past 2 days.

services/libfuzzer/libfuzzer.sh
This is causing issues with the xpcshell-webgl fuzzer.
=> [libfuzzer] Remove MOZ_HEADLESS env variable

services/grizzly-android/emulator_install.py, services/grizzly-android/setup.cfg
* Make Android boot timeout a parameter (default 120s in automation, 60s (unchanged) for command line
* Make retry delay a parameter for the @retry decorator, so it can be decreased where needed
=> [grizzly-android] Change Android boot timeouts

services/fuzzing-decision/src/fuzzing_decision/common/util.py, services/fuzzing-decision/src/fuzzing_decision/decision/workflow.py, services/fuzzing-decision/src/fuzzing_decision/pool_launch/cli.py
This is to try to workaround this:
```
INFO:fuzzing_decision.common.workflow:Cloning git@github.com:MozillaSecurity/fuzzing-tc-config.git
Warning: Permanently added the ECDSA host key for IP address '140.82.114.3' to the list of known hosts.
INFO:fuzzing_decision.common.workflow:Using cloned config files in C:\Users\TASK_1~1\AppData\Local\Temp\tmp4x2pqv49fuzzing-tc-config.git
INFO:fuzzing_decision.common.workflow:Updating repo to refs/heads/master
Traceback (most recent call last):
File "C:\Users\task_165581316691787\msys64\opt\python\lib\runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\task_165581316691787\msys64\opt\python\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File …
```
=> Try to bypass permission problems when calling rmtree

services/ci-py-310-osx/service.yaml, services/ci-py-38-osx/service.yaml, services/ci-py-39-osx/service.yaml, services/grizzly-macos/service.yaml
Seeing this failure when making a non-macos specific change in fuzzing-decision:
```
Error: Invalid formula: /Users/runner/work/orion/orion/tasks/task_165789188963172/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libgccjit.rb
libgccjit: undefined method `on_arm' for #<Class:0x00007fa0e6b331f0>
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing; `/Users/runner/work/orion/orion/tasks/task_165789188963172/homebrew/bin/brew tap homebrew/core` exited with 1.
```
I'm guessing this is just an outdated homebrew problem.
=> Update homebrew version

services/nss-coverage/launch-worker.sh, services/nss-coverage/setup.sh
* remove unused fuzzfetch recipe
* use unzip instead of 7z (7z was installed by fuzzfetch recipe)
* add basic task status reporting
* add `NO_REPORT=1` to allow running `launch-worker.sh` without reporting to CovManager for local testing
* add psmisc for killall (caused [coverage task](https://community-tc.services.mozilla.com/tasks/Lswm1TI2QZ-0uS3KfY39oA/runs/0/logs/project/fuzzing/private/logs/live.log) to fail after success)
=> NSS coverage image fixes

services/fuzzing-decision/src/fuzzing_decision/decision/pool.py, services/fuzzing-decision/tests/test_pool.py
This is to work-around https://github.com/taskcluster/taskcluster/issues/5660. When the scope list reaches a certain size, it can bloat the header size until it causes API calls to fail when the decision task runs.
Fixes #222
=> Use hook role for decision task scopes.

scripts/relocate_homebrew.sh, services/ci-py-310-osx/setup.sh, services/ci-py-38-osx/setup.sh, services/ci-py-39-osx/setup.sh
For some reason this changed since moving from Catalina to Big Sur. We need to rewrite the shebang line of scripts to make it relocatable.
=> Fix Homebrew shebang rewriting

services/orion-builder/src/orion_builder/push.py
I had to debug and push this to Docker Hub manually to un-break Orion builds. Without this, the push task was being indexed, which doesn't have the image artifacts.
=> Index the build task, not the push task itself.

services/orion-decision/src/orion_decision/cron.py, services/orion-decision/tests/test_cron.py
Timestamps come from TC as `str`. The test covering this made the same mistake.
[task UfKAypHpREGIdW030EwVyw](https://community-tc.services.mozilla.com/tasks/UfKAypHpREGIdW030EwVyw) is an example (Most recent fire from [orion-cron hook](https://community-tc.services.mozilla.com/hooks/project-fuzzing/orion-cron)).
=> Fix bug in cron

recipes/linux/cleanup.sh
These should be fixed/logged, but should not break image builds.
=> Ignore failures during cleanup.

recipes/linux/rr.sh
@pyoor reports that until https://github.com/rr-debugger/rr/pull/3362 is in an rr release, we will have problems with pernosco traces collected on Skylake CPUs. Build rr from current master until then.
=> [rr] Build rr from source until a new release is made.

services/bugmon/launch-bugmon.sh
Pin poetry to version 1.2.2 until https://github.com/python-poetry/poetry/issues/7184 is fixed.
=> [bugmon] Pin poetry to version 1.2.2

services/fuzzing-decision/src/fuzzing_decision/pool_launch/launcher.py, services/fuzzing-decision/tests/test_launch.py, services/grizzly-win/setup.sh
Only use values from pool config if they don't exist. This allows customization of one off TC tasks.
=> [fuzzing-decision] Don't overwrite existing environment

services/fuzzing-decision/setup.cfg
This can go away when aiohttp makes a release. (I think)
At install:
```
+ pip3 install --no-build-isolation -e /src/fuzzing-tc
ERROR: aiohttp 3.8.3 has requirement charset-normalizer<3.0,>=2.0, but you'll have charset-normalizer 3.0.1 which is incompatible.
+ cat /tmp/tmp.Sekeu50aDZ
Obtaining file:///src/fuzzing-tc
Preparing wheel metadata: started
Preparing wheel metadata: finished with status 'done'
Collecting taskcluster
Downloading taskcluster-47.0.3-py3-none-any.whl (141 kB)
Collecting python-dateutil
Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pyyaml
Downloading PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
Collecting async-timeout>=2.0.0
Downloading …
```
=> Force charset-normalizer version range

services/ci-py-common/setup-linux.sh
This is needed to be able to build dependencies for grizzly that are lacking a wheel (aioquic on 3.11).
=> [ci-py] Add libssl-dev

services/ci-node-14-win/service.yaml, services/ci-node-14/service.yaml, services/ci-node-16-win/service.yaml, services/ci-node-16/service.yaml, services/ci-node-18-win/service.yaml, services/ci-node-18/service.yaml, services/orion-decision/src/orion_decision/cron.py, services/orion-decision/tests/test_cron.py
Artifacts expire before the task itself, so this was causing services that need rebuild to be missed (ci-node-16 artifact is expired but not rebuilt).
=> Fix orion cron

services/orion-decision/src/orion_decision/cron.py, services/orion-decision/tests/test_cron.py
Use [queue.task()](https://community-tc.services.mozilla.com/docs/reference/platform/queue/api#task) instead of [index.findTask()](https://community-tc.services.mozilla.com/docs/reference/core/index/api#findTask) to lookup deadline.
this caused the following [failure](https://community-tc.services.mozilla.com/tasks/TlQTEz1HQs2VobCM_8SKGA):
```
Traceback (most recent call last):
File "/usr/bin/cron-decision", line 8, in <module>
sys.exit(cron_main())
^^^^^^^^^^^
File "/src/orion-decision/src/orion_decision/cli.py", line 373, in cron_main
sys.exit(CronScheduler.main(args))
^^^^^^^^^^^^^^^^^^^^^^^^
File "/src/orion-decision/src/orion_decision/cron.py", line 155, in main
sched.mark_services_for_rebuild()
File "/src/orion-decision/src/orion_decision/cron.py", line 113, in …
```
=> [orion-decision] Cron should look for deadline in task definition, not index.

services/ci-node-14-win/setup.sh, services/ci-node-16-win/setup.sh, services/ci-node-18-win/setup.sh, services/ci-py-310-win/setup.sh, services/ci-py-38-win/setup.sh, services/ci-py-39-win/setup.sh, services/coverage-revision/Dockerfile, services/credstash/Dockerfile, services/grizzly-reduce-monitor/Dockerfile, services/grizzly-win/launch.sh, services/grizzly-win/setup.sh, services/site-scout-win/launch.sh, services/site-scout-win/setup.sh
Rather than `{0..9}`, this was generating the sequence: `[0, 1, 1, 1, ...]` which never terminated, resulting in an infinite retry.
=> Fix retry function for non-bash shells.

recipes/linux/grcov.sh, recipes/linux/llvm-symbolizer.sh
In #276 we switched from the Github release binary for grcov to building it, because those binaries require 22.04. Now the cargo in 20.04 is also too old to build grcov.
Although we should update everything to 22.04 at some point, we are using the Firefox-CI toolchains for clang, etc., because then we track the versions used in m-c and they are built to support a range of Linux images.
=> Use Firefox CI version of grcov instead of building it.

services/orion-decision/src/orion_decision/__init__.py, services/orion-decision/src/orion_decision/ci_scheduler.py, services/orion-decision/src/orion_decision/cli.py, services/orion-decision/src/orion_decision/cron.py, services/orion-decision/src/orion_decision/scheduler.py, services/orion-decision/tests/test_cischeduler.py, services/orion-decision/tests/test_cron.py, services/orion-decision/tests/test_scheduler.py
This is the proper fix for https://community-tc.services.mozilla.com/hooks/project-fuzzing/orion-cron .
Propagate the decision task `schedulerId` to the tasks it creates.
=> [orion-scheduler] Don't use fixed scheduler id for created tasks.

services/fuzzing-decision/tc-admin.py
This means created/modified pools will not be run automatically, nor will removed/disabled pool tasks be killed.
To cycle a pool, either trigger its hook manually, or wait until the next scheduled cycle.
=> Don't auto-cycle for changes

services/libfuzzer/coverage.sh, services/libfuzzer/setup-target.sh
This allows setting eg. `REPO=try` and `REVISION=abc123` to run a one-off libFuzzer task in an existing pool using a try build.
=> Add REPO & allow setting REVISION

services/grizzly-win/setup.sh, services/site-scout-win/setup.sh
If we rely solely on indexed toolchain tasks, we may get esr versions instead.
=> Use taskgraph to determine which grcov toolchain to download.

services/grizzly-win/launch.sh
=> [grizzly-win] Make AV disable commands optional in case the image

services/grizzly/setup.sh
This can be removed once we update to Ubuntu 22.04.4
=> [grizzly] Use Mesa PPA to work around crash

services/coverage-revision/launch.sh
=> [coverage-revision] Download source archive as a cache for coverage tasks

services/libfuzzer/libfuzzer.sh, services/nyx/launch-root.sh, services/nyx/launch-worker.sh
This matters especially for corpus refresh, which can be very short.
=> Ensure final stats are reported

services/orion-decision/src/orion_decision/git.py
Without this it makes setuptools_scm or poetry-dynamic-versioning unable to calculate a version tag except on releases (where the tag itself is used for `git checkout`), which makes it impossible to test.
=> Fetch tags for incremental version calculations

services/grizzly/setup.sh
23.3.2 breaks xvfb-run
The stable PPA lacks dbgsyms, so disable them for now.
=> Switch to mesa stable PPA

services/libfuzzer/setup.sh
In the xpcshell libfuzzer targets, I'm frequently seeing the following error:
`Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=4.55316) [GFX1-]: glxtest: libpci missing`
Adding `libpci-dev` should address this.
=> [libfuzzer] Install libpci3

services/ci-node-14-win/setup.sh, services/ci-node-16-win/setup.sh, services/ci-node-18-win/setup.sh, services/ci-node-20-win/setup.sh, services/ci-py-310-win/setup.sh, services/ci-py-311-win/setup.sh, services/ci-py-312-win/setup.sh, services/ci-py-38-win/setup.sh, services/ci-py-39-win/setup.sh, services/grizzly-win/setup.sh, services/site-scout-win/setup.sh
Apply #386  to all windows pools. This has only been a problem for bugmon so far, but we don't know why it happened there.
=> Remove all symlinks prior to tar

services/nyx/launch-worker.sh
This allows specifying an alternate build (e.g. try)
=> Allow overriding fuzzfetch args

services/ci-py-310-win/setup.sh, services/ci-py-311-win/setup.sh, services/ci-py-312-win/setup.sh, services/ci-py-39-win/setup.sh
We have yet to find a way to install poetry cleanly using a portable python instance.  Rather than addressing that directly, we will just install poetry at runtime in any windows CI instance that requires it.
=> [ci-py-win] Remove poetry from setup

services/bugmon/launch-bugmon.sh
Bugmon never re-uses builds so there's no need to cache them.
=> [bugmon] Disable build caching

services/grizzly-reduce-monitor/src/grizzly_reduce_monitor/task_templates/reduce-windows.yaml, services/grizzly-win/launch.sh
It appears that on Windows a race may occur when specifying a directory as an artifact.  See [here](https://community-tc.services.mozilla.com/tasks/K5_NG8pwRRaZAN9MmXs1ZQ/runs/0/logs/public/logs/live.log#L194).  To avoid this, we'll compress the directory first and then attach that as an artifact.
=> [grizzly-win] Compress grizzly working directory to avoid artifact race

services/gr-css-reports/launch.sh
Fuzzfetch was removed from the base image in https://github.com/MozillaSecurity/orion/commit/004f511742efdac3c343d2b1241803e65bfe16f6.
=> [gr-css-reports] Install fuzzfetch

services/nyx/launch-worker.sh
Location in the ipc-fuzzing repository has changed, updating this accordingly.
=> Move Nyx code coverage scripts

services/fuzzing-decision/src/fuzzing_decision/common/pool.py, services/fuzzing-decision/src/fuzzing_decision/decision/pool.py, services/fuzzing-decision/src/fuzzing_decision/decision/providers.py, services/fuzzing-decision/src/fuzzing_decision/schemas/pools.yaml, services/fuzzing-decision/tests/fixtures/community/config/imagesets.yml, services/fuzzing-decision/tests/fixtures/pools/expect1.yml, services/fuzzing-decision/tests/fixtures/pools/expect10.yml, services/fuzzing-decision/tests/fixtures/pools/expect11.yml, services/fuzzing-decision/tests/fixtures/pools/expect12.yml, services/fuzzing-decision/tests/fixtures/pools/expect13.yml, services/fuzzing-decision/tests/fixtures/pools/expect2.yml, services/fuzzing-decision/tests/fixtures/pools/expect3.yml, services/fuzzing-decision/tests/fixtures/pools/expect4.yml, services/fuzzing-decision/tests/fixtures/pools/expect5.yml, services/fuzzing-decision/tests/fixtures/pools/expect6.yml, services/fuzzing-decision/tests/fixtures/pools/expect7.yml, services/fuzzing-decision/tests/fixtures/pools/expect8.yml, services/fuzzing-decision/tests/fixtures/pools/expect9.yml, services/fuzzing-decision/tests/fixtures/pools/load-cfg.yml, services/fuzzing-decision/tests/fixtures/pools/pool1.yml, services/fuzzing-decision/tests/fixtures/pools/pool4.yml, services/fuzzing-decision/tests/fixtures/pools/pool9.yml, services/fuzzing-decision/tests/fixtures/pools/pre-pool.yml, services/fuzzing-decision/tests/test_launch.py, services/fuzzing-decision/tests/test_pool.py
Valid values are [docker, generic, d2g].
`d2g` generates a docker payload with generic worker machine config.
=> Add worker field to pool configuration

services/orion-builder/Dockerfile
This is broken in yet another upstream dependency that depends on distutils.
https://community-tc.services.mozilla.com/tasks/ZyTBKqy4SYm2__ZmzS1_NA/runs/0/logs/public/logs/live.log
=> Pin base image to Alpine 3.19 for Python 3.11

services/fuzzing-decision/src/fuzzing_decision/decision/pool.py, services/orion-decision/pyproject.toml, services/orion-decision/src/orion_decision/ci_scheduler.py, services/orion-decision/src/orion_decision/cli.py, services/orion-decision/src/orion_decision/cron.py, services/orion-decision/src/orion_decision/scheduler.py, services/orion-decision/tests/test_cischeduler.py, services/orion-decision/tests/test_cron.py, services/orion-decision/tests/test_scheduler.py, services/orion-decision/tox.ini
This fixes decision tasks which are pending for longer than 15 minutes.
=> Ignore TASKCLUSTER_NOW and use current time when creating tasks

services/libfuzzer/launch.sh
Using `set -e` causes the launch script to exit immediately on any non-zero exit code.  This causes our exit code handling for `timeout` to be ignored.
=> [libfuzzer] Fix bug preventing capture of fuzzer exit code

services/libfuzzer/libfuzzer.sh
Since we're passing the full command line args to refresh now, including the non-existent corpora folder, we should make sure it exists.
=> Ensure corpora folder exists in all cases

services/libfuzzer/libfuzzer.sh
I think refresh is still failing because the `$CORPORA` arg (although unwanted) ... appears first in the list of args we pass.
libfuzzer `-merge` uses the first corpus directory as the merge destination. GFD now manages the refresh folders, but it doesn't know about `$CORPORA` appearing first, so it fails to see any result of the merge.
=> Remove corpora arg for refresh

recipes/linux/js32_deps.sh, services/langfuzz/setup.sh
Starting to add full arm64 linux support for Orion. Tried locally with langfuzz as first example, by removing the irrelevant 32 bit packages (unavailable on arm64).
=> [langfuzz] Add arm64 support

services/fuzzing-decision/src/fuzzing_decision/decision/providers.py
You'll need this change now that we have upgraded to Generic Worker version 70.0.0.
=> Enable D2G on all worker pools

services/libfuzzer/libfuzzer.sh
Previously we were calculating deadline and then calling fuzzfetch and other setup steps, which can take a variable amount of time.
=> Calculate deadline before setting timeout

recipes/linux/grcov.sh, recipes/linux/llvm-symbolizer.sh, services/langfuzz/Dockerfile, services/langfuzz/launch-langfuzz.sh, services/langfuzz/setup.sh
- update to Ubuntu 22.04
- pre-install python packages required
- use Amazon Corretto OpenJDK 11
- use gcov 9
- install arm64 grcov & llvm-symbolizer
=> Update langfuzz image

services/nss-corpus-update/launch.sh
The corpus name for the targets compiled *without* TLS fuzzing mode being `-no_fuzzer_mode` (double negation) strikes again...
=> [nss-corpus-update] Handle TLS fuzzing mode correctly

services/fuzzing-decision/src/fuzzing_decision/decision/pool.py
Allows restarting fuzzing tasks at any time until the next cycle. This matters a lot for pools where max_run_time << cycle_time
=> Use cycle time to determine deadline

services/nyx/Dockerfile, services/nyx/build_afl.sh, services/nyx/patches/hongfuzz-2b-chunked.diff, services/nyx/patches/increase-map-size.diff, services/nyx/patches/libnyx.diff, services/nyx/patches/nyx.diff
Whitespace in inlined patches can by modified by linters.  These should exist as standalone files.
=> [nyx] Move nyx patches to standalone files

services/fuzzing-decision/src/fuzzing_decision/decision/providers.py, services/fuzzing-decision/tests/test_pool.py
Recent changes to generic worker will abort the task if memory usage exceeds 90% for 5 consecutive measurements at 0.5s intervals.  See https://docs.taskcluster.net/docs/changelog?version=v83.4.0&audience=WORKER-DEPLOYERS for further information.
=> [fuzzing-decision] Disable OOM abort protection for all fuzzing tasks

services/nyx/launch-worker.sh, services/nyx/sharedir/fuzz_no_pt.sh, services/nyx/sharedir/stage2.sh
Enables dynamic instrumentation filtering.  The image now accepts the `AFL_PC_FILTER_FILE_REGEX` environment variable which defines a regex of symbols to match.
See https://github.com/AFLplusplus/AFLplusplus/blob/f590973387ee04d6c7ef016d5111313f9f4945b8/utils/dynamic_covfilter/README.md for more information.
=> Add support for AFL_PC_FILTER file

recipes/linux/common.sh
Ensures that all errors, even temporal ones, are retried.
=> [recipes] Add curl --retry-all-errors to retry-curl function

services/libfuzzer/libfuzzer.sh
Sometimes, when a task is retried, task time is set to a negative number which causes the `timeout` command to fail.  In these cases, we want to exit cleanly as this behavior is expected.
=> [libfuzzer] Exit cleanly if target time is insufficient to fuzz

services/nyx/Dockerfile, services/nyx/build_afl.sh, services/nyx/custom_mutators/web_service_mutator/Makefile, services/nyx/custom_mutators/web_service_mutator/web_service_mutator.c, services/nyx/launch-worker.sh, services/nyx/sharedir/nyx-server.py, services/nyx/sharedir/stage2.sh
Adds a custom mutator for interacting with the domino testcase generator.  This runs in the host and allows us to generate a cache of testcases.  The results are then serialized and passed to each Nyx instance.
=> [nyx] Add custom mutator for domino testcases

services/afl/Dockerfile, services/afl/launch-worker.sh, services/afl/patches/afl-cmin.patch, services/afl/setup.sh
The awk version of afl-cmin does not automatically inherit environment variables.  This PR runs afl-showmap using `AFL_PRELOAD` and `AFL_MAP_SIZE` if they are present in the environment.
=> [afl] Set AFL_MAP_SIZE AND AFL_PRELOAD for fuzzing and corpus refresh

services/nyx/launch-worker.sh
Currently, the ipc-research code coverage scripts do not work properly when dynamic PC filtering is enabled.  The cause is unknown but dynamic PC filtering is unnecessary for coverage runs regardless.  
This PR:
- disables dynamic filtering for coverage runs
- enables FAST calibration (which improves performance due to the reduced level of stability)
- includes a minor bug fix
=> Minor improvements to Nyx code coverage

services/nyx/launch-worker.sh, services/nyx/sharedir/stage2.sh
This allows us to separate variables from those necessary for all fuzz runs, and dynamically generated variables (i.e. COVERAGE, AFL_PC_FILTER_FILE, etc).
=> [nyx] Add support for session specific variables

services/fuzzilli/Dockerfile, services/fuzzilli/fuzzilli.sh, services/fuzzilli/setup.sh
Otherwise we end up with cpus/4 on x86_64 instead of cpus/2.
=> Include logical CPUs when calculating instances to run

services/gr-css-reports/launch.sh
Installing gr.css globally outside of the gr.css.reports directory ensures that it will be updated regardless of gr.css.reports dependencies.
=> feat(gr-css): install gr.css globally and update it
