MozillaSecurity/orion

base/linux/fuzzos/Dockerfile
base/linux/fuzzos/recipes/honggfuzz.sh
base/linux/fuzzos/recipes/htop.sh
base/linux/fuzzos/recipes/llvm.sh
base/linux/fuzzos/recipes/nodejs.sh
base/linux/fuzzos/recipes/radamsa.sh
base/linux/fuzzos/recipes/rg.sh
base/linux/fuzzos/recipes/rr.sh
base/linux/fuzzos/setup.sh
base/windows/fuzzos/Dockerfile
services/ci-py-27/Dockerfile
services/ci-py-35/Dockerfile
services/ci-py-36/Dockerfile
services/ci-py-37/Dockerfile
services/ci-py-38/Dockerfile
services/credstash/Dockerfile
services/funfuzz/Dockerfile
services/grizzly/recipes/cloudwatch.sh
services/grizzly/recipes/fuzzfetch.sh
services/grizzly/recipes/redis.sh
services/grizzly/recipes/setup.sh
services/libfuzzer/Dockerfile
services/linter/Dockerfile
services/u2f-hid-rs/Dockerfile

- add retries where missing
- move radamsa to fuzzos base
- update maintainer labels

Cleanup of Orion.

---

services/libfuzzer/libfuzzer.sh

using macro `S3_CORPUS_REFRESH`

[libfuzzer] Add support for S3 corpus refresh 

---

recipes/linux/llvm.sh
services/grizzly/Dockerfile
services/grizzly/setup.sh

This also changes the default installed LLVM from 8 to 10.

[grizzly] Switch grizzly to ubuntu 20.04.

---

services/orion-decision/src/orion_decision/orion.py
services/orion-decision/tests/fixtures/services03/test4/Dockerfile
services/orion-decision/tests/fixtures/services03/test4/service.yaml
services/orion-decision/tests/test_orion.py

Fix and add a test.
Fixes #81.

Services not marked dirty when recipe basename used.

---

services/gr-css-reports/Dockerfile
services/gr-css-reports/launch.sh
services/gr-css-reports/service.yaml
services/gr-css-reports/setup.sh
services/gr-css-reports/ssh_config

Add image for use with gr-css cron hook.

[gr-css] Initial commit

---

services/fuzzing-decision/service.yaml
services/fuzzing-decision/setup.cfg
services/fuzzing-decision/tests/conftest.py
services/fuzzing-decision/tests/test_pool.py
services/grizzly-reduce-monitor/setup.cfg

... to make it easier for services using TC to resolve dependencies.

Loosen TC requirements 

---

.taskcluster.yml
services/orion-builder/Dockerfile
services/orion-builder/setup.cfg
services/orion-builder/src/orion_builder/cli.py
services/orion-builder/src/orion_builder/stage_deps.py
services/orion-decision/src/orion_decision/task_templates/build.yaml

This should eliminate out-of-space errors in docker builds.

Builder use overlayfs

---

services/bugmon/Dockerfile
services/bugmon/setup.sh
services/funfuzz/setup.sh
services/gr-css-reports/Dockerfile
services/gr-css-reports/launch.sh
services/gr-css-reports/setup.sh
services/grizzly/Dockerfile

Cleanup recipe usage in grizzly and derivatives

---

services/ci-node-14/Dockerfile
services/ci-node-14/service.yaml

Adds an image for node 14 with npm 7.

[ci-node-14] Initial commit

---

services/libfuzzer/libfuzzer.sh
services/libfuzzer/setup-target.sh
services/libfuzzer/setup.sh

Adds setup and fuzzing paths for xpcrt targets.
Depends on https://github.com/MozillaSecurity/fuzzfetch/pull/93

[libfuzzer] Initial attempt at supporting xpcrt

---

services/fuzzing-decision/src/fuzzing_decision/common/pool.py
services/fuzzing-decision/src/fuzzing_decision/decision/pool.py
services/fuzzing-decision/tests/fixtures/pools/expect1.yml
services/fuzzing-decision/tests/fixtures/pools/expect10.yml
services/fuzzing-decision/tests/fixtures/pools/expect11.yml
services/fuzzing-decision/tests/fixtures/pools/expect2.yml
services/fuzzing-decision/tests/fixtures/pools/expect3.yml
services/fuzzing-decision/tests/fixtures/pools/expect4.yml
services/fuzzing-decision/tests/fixtures/pools/expect5.yml
services/fuzzing-decision/tests/fixtures/pools/expect6.yml
services/fuzzing-decision/tests/fixtures/pools/expect7.yml
services/fuzzing-decision/tests/fixtures/pools/expect8.yml
services/fuzzing-decision/tests/fixtures/pools/expect9.yml
services/fuzzing-decision/tests/fixtures/pools/load-cfg.yml
services/fuzzing-decision/tests/fixtures/pools/pool1.yml
services/fuzzing-decision/tests/fixtures/pools/pool4.yml
services/fuzzing-decision/tests/fixtures/pools/pool9.yml
services/fuzzing-decision/tests/fixtures/pools/pre-pool.yml
services/fuzzing-decision/tests/fixtures/pools/pre.yml
services/fuzzing-decision/tests/test_launch.py
services/fuzzing-decision/tests/test_pool.py

One Windows, this adds the user to Administrators group and runs the task commands with Administrator privileges.

Add `run_as_admin` field to fuzzing-tc-config.

---

services/grizzly-reduce-monitor/src/grizzly_reduce_monitor/monitor.py
services/grizzly-reduce-monitor/src/grizzly_reduce_monitor/task_templates/reduce-android.yaml

Depends on https://github.com/mozilla/community-tc-config/pull/485

[grizzly-reduce-monitor] Add grizzly reduce queue for android.

---

services/prefmonitor/Dockerfile
services/prefmonitor/launch.sh
services/prefmonitor/service.yaml
services/prefmonitor/setup.sh
services/prefmonitor/ssh_config

Run's prefmonitor and opens issues on https://github.com/MozillaSecurity/prefpicker when a pref's dependencies have been closed.

[prefmonitor] Add image for routinely running prefmonitor

---

services/grizzly-reduce-monitor/src/grizzly_reduce_monitor/monitor.py

... for non-Linux crashes if they don't repro on Linux.

[grizzly-reduce-monitor] Set output quality to Q6

---

services/orion-decision/service.yaml
services/orion-decision/setup.cfg
services/orion-decision/src/orion_decision/__init__.py
services/orion-decision/src/orion_decision/ci_check.py
services/orion-decision/src/orion_decision/ci_matrix.py
services/orion-decision/src/orion_decision/ci_scheduler.py
services/orion-decision/src/orion_decision/cli.py
services/orion-decision/src/orion_decision/cron.py
services/orion-decision/src/orion_decision/git.py
services/orion-decision/src/orion_decision/orion.py
services/orion-decision/src/orion_decision/scheduler.py
services/orion-decision/tests/conftest.py
services/orion-decision/tests/fixtures/services03/README.md
services/orion-decision/tests/test_cimatrix.py
services/orion-decision/tests/test_cischeduler.py
services/orion-decision/tests/test_cli.py
services/orion-decision/tests/test_cron.py
services/orion-decision/tests/test_gitrepo.py
services/orion-decision/tests/test_orion.py
services/orion-decision/tests/test_scheduler.py
services/orion-decision/tox.ini

This is intended to run in a hook weekly to check indexed tasks for any that would expire in the next week and rebuild them.
Fixes #140

Add a periodic scheduler.

---

services/fuzzilli/fuzzilli.sh

This adds the fuzzilli-differential repository containing a Fuzzilli fork that can be used for advanced differential testing with our codebase.

Add fuzzilli-differential repository for testing

---

services/fuzzing-decision/src/fuzzing_decision/common/workflow.py

This will require changes in fuzzing config repo `.taskcluster.yml` too.

Use git clone method from orion-decision

---

services/fuzzing-decision/src/fuzzing_decision/decision/pool.py
services/fuzzing-decision/tests/fixtures/pools/expect-task-map2.yml
services/fuzzing-decision/tests/fixtures/pools/map2.yml
services/fuzzing-decision/tests/test_pool.py

Use real pool id for generating scopes.

---

services/grizzly-android/setup.sh

Clang download has been failing for a while. Use latest clang instead (script copied from [nss-coverage image](https://github.com/MozillaSecurity/orion/commit/12d17c4348dda066fcc929b53d9a1a75a2410928#diff-334f057eee2c34bfa482e20d422d60e949f1770f1c2b2177f17a95381623d1e5R36-R50)).

[grizzly-android] Use latest clang

---

services/grizzly-win/setup.sh

We frequently see DNS resolution failures on Windows.

[grizzly-win] Retry curl downloads during setup.

---

services/orion-builder/Dockerfile
services/orion-builder/setup.cfg
services/orion-builder/src/orion_builder/stage_deps.py
services/orion-builder/tox.ini

* fix openssl command-line broken by upstream version change
* update task-boot to 0.3.5
* update Docker registry to 2.8.1
* update img revision

Fix & update orion-builder

---

.pre-commit-config.yaml
services/ci-node-16/Dockerfile
services/orion-builder/Dockerfile
services/orion-builder/podman.patch
services/orion-builder/src/orion_builder/build.py
services/orion-builder/src/orion_builder/push.py
services/orion-builder/src/orion_builder/stage_deps.py
services/orion-decision/src/orion_decision/task_templates/build.yaml
services/orion-decision/src/orion_decision/task_templates/push.yaml
services/orion-decision/src/orion_decision/task_templates/recipe_test.yaml

Use podman in place of img

---

recipes/linux/common.sh
recipes/linux/dbgsyms.sh
recipes/linux/ff32_deps.sh
recipes/linux/fluentbit.sh
recipes/linux/llvm.sh
services/grizzly/setup.sh

This will need to be rebased on #235 for CI to pass.

[grizzly] Add Linux32 runtime dependencies

---

services/nss-coverage/launch-worker.sh
services/nss-coverage/setup.sh

& increase runtime per target to 1hr by default.

[nss] Patch coverage builds against clang-15 error.

---

recipes/linux/rr.sh

Includes https://github.com/rr-debugger/rr/issues/3408

[rr] Update rr

---

services/orion-decision/src/orion_decision/task_templates/push.yaml

Env vars must be strings (soon to be enforced)

---

services/gr-css-reports/launch.sh

The pre-release branches for the gr.css related projects have all been merged to main.

[gr-css-reports] Checkout stable release branches

---

services/grizzly-macos/launch.sh
services/grizzly-win/launch.sh
services/grizzly/launch-grizzly-worker.sh

[grizzly] Add cloud storage creds

---

services/grizzly-win/launch.sh
services/site-scout-win/launch.sh

We do this on Linux and it should improve performance.

[grizzly-win] Enable fluentbit db locking option

---

services/fuzzing-decision/README.md
services/fuzzing-decision/src/fuzzing_decision/common/workflow.py
services/fuzzing-decision/tests/test_workflow.py

Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1857024.
Please also update your references in any private repos you may have.

chore: update community-tc-config links

---

services/nyx/launch-worker.sh
services/nyx/setup.sh

Depends on https://github.com/MozillaSecurity/guided-fuzzing-daemon/pull/21

Build and sometimes use custom honggfuzz mutator

---

services/bugmon-win/setup.sh
services/ci-node-14-win/setup.sh
services/ci-node-16-win/setup.sh
services/ci-node-18-win/setup.sh
services/ci-py-310-osx/setup.sh
services/ci-py-310-win/setup.sh
services/ci-py-311-osx/setup.sh
services/ci-py-311-win/setup.sh
services/ci-py-312-osx/setup.sh
services/ci-py-312-win/setup.sh
services/ci-py-38-osx/setup.sh
services/ci-py-38-win/setup.sh
services/ci-py-39-osx/setup.sh
services/ci-py-39-win/setup.sh
services/coverage-revision/Dockerfile
services/credstash/Dockerfile
services/fuzzing-decision/Dockerfile
services/grizzly-reduce-monitor/Dockerfile
services/grizzly-win/setup.sh
services/orion-builder/Dockerfile
services/orion-builder/podman.patch
services/orion-builder/setup.cfg
services/orion-builder/tox.ini
services/orion-decision/Dockerfile
services/site-scout-win/setup.sh

Also make setups more consistent.

Fix Alpine python installations since PEP 668 was enabled.

---

services/bugmon-win/setup.sh
services/ci-node-14-win/setup.sh
services/ci-node-16-win/setup.sh
services/ci-node-18-win/setup.sh
services/ci-py-310-win/setup.sh
services/ci-py-311-win/setup.sh
services/ci-py-312-win/setup.sh
services/ci-py-38-win/setup.sh
services/ci-py-39-win/setup.sh
services/grizzly-win/setup.sh
services/site-scout-win/setup.sh

This is to fix https://github.com/taskcluster/taskcluster/issues/6791.
Needs to be tested with a fuzzing task before merge.

[windows] Remove problematic symlink which prevents extraction under g-w

---

services/site-scout-win/launch.sh

[site-scout] Fix typo

---

services/nyx/setup.sh

[bug 1877478](https://bugzilla.mozilla.org/show_bug.cgi?id=1877478)

Update AFL++ version to match bug 1877478

---

.pre-commit-config.yaml
services/fuzzing-decision/src/fuzzing_decision/decision/pool.py
services/fuzzing-decision/src/fuzzing_decision/decision/providers.py
services/fuzzing-decision/tests/test_pool.py

This does not change the payload (ie. d2g translation will occur)

[fuzzing-decision] Use generic-worker in all cases.

---

services/site-scout-win/launch.sh
services/site-scout/launch-worker.sh

Put launch failures in a location where they will be collected as artifacts.

[site-scout] Create directory for launch failures

---

services/nyx/launch-worker.sh
services/nyx/setup.sh

description here: https://github.com/AFLplusplus/AFLplusplus/pull/2027

Add patch for invalid payload write

---

.github/scripts/start-worker.sh

[ci] Fix darwin generic worker binary name

---

services/fuzzing-decision/src/fuzzing_decision/common/pool.py
services/fuzzing-decision/src/fuzzing_decision/decision/pool.py
services/fuzzing-decision/src/fuzzing_decision/schemas/pools.yaml
services/fuzzing-decision/tests/fixtures/pools/expect-task-map2.yml
services/fuzzing-decision/tests/fixtures/pools/expect1.yml
services/fuzzing-decision/tests/fixtures/pools/expect10.yml
services/fuzzing-decision/tests/fixtures/pools/expect11.yml
services/fuzzing-decision/tests/fixtures/pools/expect12.yml
services/fuzzing-decision/tests/fixtures/pools/expect13.yml
services/fuzzing-decision/tests/fixtures/pools/expect2.yml
services/fuzzing-decision/tests/fixtures/pools/expect3.yml
services/fuzzing-decision/tests/fixtures/pools/expect4.yml
services/fuzzing-decision/tests/fixtures/pools/expect5.yml
services/fuzzing-decision/tests/fixtures/pools/expect6.yml
services/fuzzing-decision/tests/fixtures/pools/expect7.yml
services/fuzzing-decision/tests/fixtures/pools/expect8.yml
services/fuzzing-decision/tests/fixtures/pools/expect9.yml
services/fuzzing-decision/tests/fixtures/pools/map2.yml
services/fuzzing-decision/tests/fixtures/pools/pool1.yml
services/fuzzing-decision/tests/fixtures/pools/pool2.yml
services/fuzzing-decision/tests/fixtures/pools/pool3.yml
services/fuzzing-decision/tests/fixtures/pools/pool4.yml
services/fuzzing-decision/tests/fixtures/pools/pool5.yml
services/fuzzing-decision/tests/fixtures/pools/pool6.yml
services/fuzzing-decision/tests/fixtures/pools/pool9.yml
services/fuzzing-decision/tests/fixtures/pools/pre.yml
services/fuzzing-decision/tests/test_pool.py

Adds routes defined in task configuration files to be applied to created tasks.

Apply routes from configuration file to task

---

services/fuzzilli/fuzzilli.sh
services/libfuzzer/libfuzzer.sh
services/nyx/launch-worker.sh

Also make bash format more consistent.

Final stats report should not fail if file is missing.

---

services/libfuzzer/libfuzzer.sh
services/nyx/launch-worker.sh

Required to match changes in https://github.com/MozillaSecurity/guided-fuzzing-daemon/pull/31

Fix guided-fuzzing-daemon arguments.

---

services/orion-decision/src/orion_decision/ci_check.py

It was ignoring `.taskcluster.yml` files using generic-worker & podman directly.

Fix CI check pre-commit hook.

---

services/nyx/launch-worker.sh
services/nyx/setup.sh

This also fixes guided-fuzzing-daemon installation in ubuntu 22.04

Update AFL++ to match m-c version

---

services/libfuzzer/libfuzzer.sh
services/nyx/launch-worker.sh

for https://github.com/MozillaSecurity/guided-fuzzing-daemon/pull/38

Update guided-fuzzing-daemon args

---

services/libfuzzer/libfuzzer.sh
services/nyx/launch-worker.sh

Recent changes to the guided-fuzzing-daemon's arg handling were not correctly reflected here.

Guided fuzzing args

---

services/nss-coverage/Dockerfile
services/nss-coverage/launch-worker.sh
services/nss-coverage/libfuzzer-options.py
services/nss-coverage/setup.sh

https://bugzilla.mozilla.org/show_bug.cgi?id=1835242

Add CryptoFuzz coverage to NSS 

---

services/nss-coverage/launch-worker.sh

[nss-coverage] Clone correct corpus for tls mode targets

---

services/fuzzing-decision/src/fuzzing_decision/decision/providers.py
services/fuzzing-decision/tests/test_pool.py

Needed for https://github.com/taskcluster/taskcluster/releases/tag/v77.0.0

fix: move d2g config for v77

---

services/fuzzing-decision/src/fuzzing_decision/decision/providers.py
services/fuzzing-decision/tests/test_pool.py

[fuzzing-decision] Fix windows by removing enableInteractive from g-w

---

services/nss-corpus-update/launch.sh
services/nss-corpus-update/setup.sh

Depends on: https://bugzilla.mozilla.org/show_bug.cgi?id=1936001.

[nss-corpus-update] Use frida hooks for corpus collection

---

services/nss-coverage/launch-worker.sh

Also make sure we build Cryptofuzz with non-TLS fuzzing mode NSS.

fix(nss-coverage): update cryptofuzz corpus
